name       : gnucash
version    : '3.0'
release    : 2
source     :
    - https://github.com/Gnucash/gnucash/releases/download/3.0/gnucash-3.0.tar.bz2 : 4c754476a5b80a97abacaeadac64fefc5a68fcfec15967908dbe3c9f7370dbb9
license    : GPL-2.0-or-later
component  : office.finance
summary    : GnuCash is personal and small-business financial-accounting software.
description: |
    GnuCash is personal and small-business financial-accounting software. Designed to be easy to use, yet powerful and flexible, GnuCash allows you to track bank accounts, stocks, income and expenses. As quick and intuitive to use as a checkbook register, it is based on professional accounting principles to ensure balanced books and accurate reports.
libsplit   : no
builddeps  :
    - pkgconfig(aqbanking)
    - pkgconfig(bdw-gc)
    - pkgconfig(dbi)
    - pkgconfig(guile-2.0)
    - pkgconfig(gwenhywfar)
    - pkgconfig(libofx)
    - pkgconfig(libxslt)
    - pkgconfig(webkit2gtk-4.0)
    - gtest-devel
    - libboost-devel
    - libdbi-drivers
setup      : |
    %patch -p1 < $pkgfiles/gnucash-gmock-shared.patch
    %cmake -DCOMPILE_GSCHEMAS=NO .
build      : |
    %make
install    : |
    %make_install
