name       : gnucash
version    : '3.5'
release    : 11
source     :
    - https://github.com/Gnucash/gnucash/releases/download/3.5/gnucash-3.5.tar.bz2 : 776d0b51b6029e25b5c7e9eb86021d5ecf1b09d8f3241b279f76dba9cc3b7745
license    : GPL-2.0-or-later
component  : office.finance
summary    : GnuCash is personal and small-business financial-accounting software
description: |
    GnuCash is personal and small-business financial-accounting software. Designed to be easy to use, yet powerful and flexible, GnuCash allows you to track bank accounts, stocks, income and expenses. As quick and intuitive to use as a checkbook register, it is based on professional accounting principles to ensure balanced books and accurate reports.
libsplit   : no
builddeps  :
    - pkgconfig(aqbanking)
    - pkgconfig(bdw-gc)
    - pkgconfig(dbi)
    - pkgconfig(guile-2.0)
    - pkgconfig(gwenhywfar)
    - pkgconfig(libofx)
    - pkgconfig(libxslt)
    - pkgconfig(webkit2gtk-4.0)
    - gtest-devel
    - libboost-devel
    - libdbi-drivers
setup      : |
    %cmake -DCOMPILE_GSCHEMAS=NO .
build      : |
    %make
install    : |
    %make_install
