name       : gnucash
version    : '4.8'
release    : 33
source     :
    - https://github.com/Gnucash/gnucash/releases/download/4.8/gnucash-4.8.tar.bz2 : 15b8e4ff8336168eba88ef2faade377e5c5ff08e48b4660da1a33a8a407feb12
license    : GPL-2.0-or-later
component  : office.finance
summary    : GnuCash is personal and small-business financial-accounting software
description: |
    GnuCash is personal and small-business financial-accounting software. Designed to be easy to use, yet powerful and flexible, GnuCash allows you to track bank accounts, stocks, income and expenses. As quick and intuitive to use as a checkbook register, it is based on professional accounting principles to ensure balanced books and accurate reports.
libsplit   : no
builddeps  :
    - pkgconfig(aqbanking)
    - pkgconfig(bdw-gc)
    - pkgconfig(dbi)
    - pkgconfig(guile-2.0)
    - pkgconfig(gwenhywfar)
    - pkgconfig(libofx)
    - pkgconfig(libxslt)
    - pkgconfig(webkit2gtk-4.0)
    - gtest-devel
    - libboost-devel
    - libdbi-drivers
    - swig
setup      : |
    %cmake -DCOMPILE_GSCHEMAS=NO .
build      : |
    %make
install    : |
    %make_install
