name       : gnucash
version    : 2.6.7
release    : 1
source     :
    - http://downloads.sourceforge.net/sourceforge/gnucash/gnucash-2.6.7.tar.bz2 : 6c15b12eeddc095d6926d9ea84d885c20b8f52781602c15aa3f672a1f7e2beef
license    : GPL-3.0
summary    : GnuCash is personal and small-business financial-accounting software.
description: |
    GnuCash is personal and small-business financial-accounting software. Designed to be easy to use, yet powerful and flexible, GnuCash allows you to track bank accounts, stocks, income and expenses. As quick and intuitive to use as a checkbook register, it is based on professional accounting principles to ensure balanced books and accurate reports.
builddeps  :
    - pkgconfig(guile-2.0)
    - pkgconfig(gtk+-2.0)
setup      : |
    %configure --disable-dbi
build      : |
    %make
install    : |
    %make_install
